# Generated by Django 4.0 on 2022-05-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'В ожидании'), ('Approved', 'Одобренный'), ('Delivered', 'Доставленный')], default='Pending', max_length=150),
        ),
    ]
