# Generated by Django 4.0 on 2022-05-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('ожидании', 'ожидании'), ('Одобренный', 'Одобренный'), ('Доставленный', 'Доставленный')], default='ожидании', max_length=150),
        ),
    ]
